resources:
  containers:
  - container: arm64v8-test-container
    image: electron.azurecr.io/arm64v8-4fc81b50f9c0980699d329bc32062fac20a26701
    options: --shm-size 128m

jobs:
- job: Test_Arm64
  container: arm64v8-test-container
  displayName: Test Arm64 on Arm64 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
